server:
  port: 9988

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/mathedu
    username: root
    password: 1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 60MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#springdoc:
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  api-docs:
#    groups:
#      enabled: true
#  swagger-ui:
#    operations-sorter: alpha
#    tags-sorter: alpha
#    path: /swagger
#    disable-swagger-default-url: true
#    doc-expansion: none
#  paths-to-match:
#    - /api/**
mathedu:
  filepath:
    notice: /home/mathedu/notice
    bbs: /home/mathedu/bbs
    teacher: /home/mathedu/image/teacher
    student: /home/mathedu/image/student
  apiinfo:
    version: 0.0.1
    title: Mathedu API Docs
    description: Mathedu API Swagger Docs
